use serde::{Deserialize, Serialize};
use serde_with::skip_serializing_none;

/**
 * Snapshot of Discord's detectable games database, generated by
 * `tools/updater`. Used for offline startup.
 */
pub const BUNDLED_DETECTABLE: &str = include_str!("../resources/detectable.json");

/**
 * Trim a raw detectable games database down to the fields rsrpc actually
 * uses: `id`/`name`/`hook`/`aliases`, `executables{name,is_launcher,os,arguments}`
 * and `third_party_skus{distributor,id}`.
 *
 * Shared by the process scanner, the CLI and `tools/updater` so the copies
 * never drift apart.
 */
pub fn trim_detectable(body: &str) -> Result<String, Box<dyn std::error::Error>> {
  Ok(serde_json::to_string(&trim_detectable_value(body)?)?)
}

/**
 * Trimmed database as a JSON value: same content as [`trim_detectable`]
 * without the final serialization round-trip. Fallback for bodies whose
 * entries miss required fields (it defaults them) when the direct struct
 * parse fails; prefer parsing directly whenever possible (zero DOM).
 */
pub fn trim_detectable_value(body: &str) -> Result<serde_json::Value, Box<dyn std::error::Error>> {
  let games: Vec<serde_json::Value> = serde_json::from_str(body)?;
  let trimmed: Vec<serde_json::Value> = games
    .into_iter()
    .map(|game| {
      let mut entry = serde_json::Map::new();
      entry.insert(
        "id".to_string(),
        game.get("id").cloned().unwrap_or_else(|| "".into()),
      );
      entry.insert(
        "name".to_string(),
        game.get("name").cloned().unwrap_or_else(|| "".into()),
      );
      entry.insert(
        "hook".to_string(),
        game.get("hook").cloned().unwrap_or_else(|| false.into()),
      );
      // Keep aliases (alternative titles): the scanner indexes matchable
      // ones for stem/folder matching. Empty/missing stays missing so the
      // trimmed snapshot carries no dead weight.
      if let Some(aliases) = game.get("aliases").and_then(|v| v.as_array()) {
        let kept: Vec<serde_json::Value> = aliases
          .iter()
          .filter_map(|a| a.as_str())
          .filter(|a| !a.trim().is_empty())
          .map(|a| serde_json::Value::String(a.to_string()))
          .collect();
        if !kept.is_empty() {
          entry.insert("aliases".to_string(), serde_json::Value::Array(kept));
        }
      }
      let executables: Vec<serde_json::Value> = game
        .get("executables")
        .and_then(|v| v.as_array())
        .map(|executables| {
          executables
            .iter()
            .map(|exe| {
              let mut m = serde_json::Map::new();
              m.insert(
                "name".to_string(),
                exe.get("name").cloned().unwrap_or_else(|| "".into()),
              );
              m.insert(
                "is_launcher".to_string(),
                exe
                  .get("is_launcher")
                  .cloned()
                  .unwrap_or_else(|| false.into()),
              );
              m.insert(
                "os".to_string(),
                exe.get("os").cloned().unwrap_or_else(|| "".into()),
              );
              if let Some(args) = exe.get("arguments")
                && !args.as_str().unwrap_or_default().is_empty()
              {
                m.insert("arguments".to_string(), args.clone());
              }
              serde_json::Value::Object(m)
            })
            .collect()
        })
        .unwrap_or_default();
      entry.insert(
        "executables".to_string(),
        serde_json::Value::Array(executables),
      );
      // Keep third-party store ids (Steam AppId etc) for automatic matching
      // of games that ship empty `executables` (e.g. How to Fish).
      let skus: Vec<serde_json::Value> = game
        .get("third_party_skus")
        .and_then(|v| v.as_array())
        .map(|skus| {
          skus
            .iter()
            .filter_map(|sku| {
              let distributor = sku.get("distributor")?.as_str()?;
              let id = sku.get("id").map(|v| match v {
                serde_json::Value::String(s) => s.clone(),
                other => other.to_string().trim_matches('"').to_string(),
              })?;
              if distributor.is_empty() || id.is_empty() {
                return None;
              }
              let mut m = serde_json::Map::new();
              m.insert("distributor".to_string(), distributor.into());
              m.insert("id".to_string(), id.into());
              Some(serde_json::Value::Object(m))
            })
            .collect()
        })
        .unwrap_or_default();
      entry.insert(
        "third_party_skus".to_string(),
        serde_json::Value::Array(skus),
      );
      serde_json::Value::Object(entry)
    })
    .collect();
  Ok(serde_json::Value::Array(trimmed))
}

#[skip_serializing_none]
#[derive(Serialize, Deserialize, Clone, Debug)]
#[serde(rename_all = "snake_case")]
pub struct DetectableActivity {
  #[serde(rename = "bot_public")]
  pub bot_public: Option<bool>,
  #[serde(rename = "bot_require_code_grant")]
  pub bot_require_code_grant: Option<bool>,
  #[serde(rename = "cover_image")]
  pub cover_image: Option<String>,
  pub description: Option<String>,
  #[serde(default)]
  pub developers: Option<Vec<Developer>>,
  #[serde(default)]
  pub executables: Option<Vec<Executable>>,
  pub flags: Option<i64>,
  #[serde(rename = "guild_id")]
  pub guild_id: Option<String>,
  pub hook: bool,
  pub icon: Option<String>,
  pub id: String,
  pub name: String,
  #[serde(default)]
  pub publishers: Option<Vec<Publisher>>,
  #[serde(rename = "rpc_origins")]
  #[serde(default)]
  pub rpc_origins: Option<Vec<String>>,
  pub splash: Option<String>,
  #[serde(rename = "third_party_skus")]
  #[serde(default)]
  pub third_party_skus: Option<Vec<ThirdPartySku>>,
  #[serde(rename = "type")]
  pub type_field: Option<i64>,
  #[serde(rename = "verify_key")]
  pub verify_key: Option<String>,
  #[serde(rename = "primary_sku_id")]
  pub primary_sku_id: Option<String>,
  pub slug: Option<String>,
  #[serde(default)]
  pub aliases: Option<Vec<String>>,
  pub overlay: Option<bool>,
  #[serde(rename = "overlay_compatibility_hook")]
  pub overlay_compatibility_hook: Option<bool>,
  #[serde(rename = "privacy_policy_url")]
  pub privacy_policy_url: Option<String>,
  #[serde(rename = "terms_of_service_url")]
  pub terms_of_service_url: Option<String>,
  #[serde(rename = "eula_id")]
  pub eula_id: Option<String>,
  #[serde(rename = "deeplink_uri")]
  pub deeplink_uri: Option<String>,
  #[serde(default)]
  pub tags: Option<Vec<String>>,
  pub pid: Option<u64>,
  pub timestamp: Option<u64>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Developer {
  pub id: String,
  pub name: String,
}

#[skip_serializing_none]
#[derive(Serialize, Deserialize, Clone, Debug)]
#[serde(rename_all = "snake_case")]
pub struct Executable {
  pub is_launcher: bool,
  pub name: String,
  pub os: String,
  pub arguments: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Publisher {
  pub id: String,
  pub name: String,
}

#[skip_serializing_none]
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ThirdPartySku {
  pub distributor: String,
  pub id: Option<String>,
  pub sku: Option<String>,
}

/// Discord's game-detection exclusions (`GET /games/detectable/exclusions`):
/// process basenames that must never match (`executables`) plus regex
/// patterns against the basename (`patterns`, e.g. installers, crash
/// reporters, `vcredist.*\.exe$`). The scanner drops these processes
/// before any matching, so they cost one basename lookup instead of a
/// full probe chain — and can never shadow a real game.
#[derive(Clone, Debug, Default)]
pub struct Exclusions {
  /// Lowercased basenames, exact match (hash set: consulted per process
  /// per tick, so O(1) instead of a linear scan over two dozen names).
  pub executables: std::collections::HashSet<String>,
  /// Compiled case-insensitively (the DB is Windows-centric; matching
  /// stays correct for Proton paths). Invalid patterns are skipped at
  /// parse, never fatal.
  pub patterns: Vec<regex::Regex>,
}

impl Exclusions {
  /// Basename already normalized (lowercase, `/`-separated path): `true`
  /// when this process must stay invisible to detection.
  pub fn is_excluded(&self, basename: &str) -> bool {
    if self.executables.is_empty() && self.patterns.is_empty() {
      return false;
    }
    if self.executables.contains(basename) {
      return true;
    }
    self.patterns.iter().any(|re| re.is_match(basename))
  }
}

/**
 * Parse an exclusions body. Tolerant by design (best-effort background
 * data): missing sections become empty, non-string entries and invalid
 * regexes are skipped, a wholly invalid body yields empty exclusions
 * instead of an error — callers keep serving the previous set.
 */
pub fn parse_exclusions(body: &str) -> Exclusions {
  let mut exclusions = Exclusions::default();
  let value: serde_json::Value = match serde_json::from_str(body) {
    Ok(value) => value,
    Err(_) => return exclusions,
  };
  if let Some(executables) = value.get("executables").and_then(|v| v.as_array()) {
    exclusions.executables = executables
      .iter()
      .filter_map(|e| e.as_str())
      .map(|e| e.trim().to_lowercase())
      .filter(|e| !e.is_empty())
      .collect();
  }
  if let Some(patterns) = value.get("patterns").and_then(|v| v.as_array()) {
    exclusions.patterns = patterns
      .iter()
      .filter_map(|p| p.as_str())
      .filter(|p| !p.trim().is_empty())
      .filter_map(|p| regex::Regex::new(&format!("(?i){p}")).ok())
      .collect();
  }
  exclusions
}
