name: Code quality and formatting

on:
  push:
    paths:
      - '.github/workflows/code_quality.yml'
      - 'lib/**'
      - 'cli/**'
      - 'tools/**'
      - 'plugin/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rustfmt.toml'
  pull_request:
    paths:
      - '.github/workflows/code_quality.yml'
      - 'lib/**'
      - 'cli/**'
      - 'tools/**'
      - 'plugin/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rustfmt.toml'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt check
        run: cargo fmt --manifest-path ./Cargo.toml --workspace -- --check

  clippy:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt

      - name: Generate detectable snapshot
        run: cargo run --manifest-path tools/updater/Cargo.toml

      - name: Clippy check
        run: cargo clippy --manifest-path ./Cargo.toml --workspace --all-targets -- -D warnings